# ポートの設定（Renderで必須の設定）
server.port=10000

# データベースの接続情報
spring.datasource.url=jdbc:postgresql://dpg-d6v075s50q8c739bnk6g-a/juggler_db
spring.datasource.username=juggler_db_user
spring.datasource.password=Go5UQrD723wJosB9589JBa2Q9F1D0J1s
spring.datasource.driver-class-name=org.postgresql.Driver

# 動作設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
